### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by mikeal** [iojs/iojs-mk#1]
Welcome, new localizations team :)

To get this team up and running you have a few initial tasks to accomplish:
- [x] Create a README.md for this repository, it should include:
  - [x] A "call to action" pointing to the Issue tracker for new translators to find tasks.
  - [x] A list of the team members.
  - [ ] Instructions on how to log an issue to be added to this team.
- [x] Set the repository description. This should not be in English, it should be in the language for this community :)
- [ ] Social Media
  - [x] Create a twitter account for this language. Share the password privately with the team.
  - [ ] Create accounts on other social media popular in this language. Share the passwords private with the rest of the team.
  - [ ] Make sure you use these accounts not just to promote newly translated material but also to attract people in your community to help with translation tasks.
  - [ ] _Optional:_ If you plan to do a Google hangout w/ your localization team have @mikeal add you to the Google+ account so that it can post to the `iojs` YouTube channel. Once you are added there is [documentation on how to setup a hangout-on-air](https://github.com/iojs/io.js/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event).
- [ ] Finally, create a new Issue to translate and publish the [latest io.js post](https://medium.com/@iojs). Once translated you should post it wherever you think it will get the most visibility to the community speaking you language, you don't have to post it to Medium unless you think that it is best.

**Comment by azder** [comment]
Um... do I need permissions to actually be able to create files, clone it locally etc?
 Right now I'm at 
"This repository is empty."
and
"ERROR: Permission to iojs/iojs-mk.git denied to azder.
fatal: Could not read from remote repository."

**Comment by mikeal** [comment]
You have to accept the invitation to the iojs group :) Should be a banner at the top of https://github.com/iojs or in your email inbox.

**Comment by azder** [comment]
thanks, I'm kinda new to work in organizations on github

**Comment by tunnckoCore** [comment]
Macedonian... xahxhahxha This is bulgarian dialect, as dialect in Varna, as dialect in Plovdiv and etc.

So add repo for BG :) I'll help.

**Comment by tunnckoCore** [comment]
Count me for BG and MK :)

**Comment by azder** [comment]
Please check nationalism at the login page, there is a standard Macedonian language defined regardless of if it is a dialect of Bulgarian or Bulgarian a dialect of Macedonian or both of Serbian etc. 

This one project is made to follow as closely as the standard Macedonian language as defined by the country of Macedonia based on dialects central to the republic as opposed to the standard Bulgarian language based on the Plovidiv area of dialects.

**Comment by tunnckoCore** [comment]
> Please check nationalism at the login page

Yep, sorry, lol. Just peak.

**Comment by Trott** [comment]
Closing as the group is dormant and the issue is stale. If it starts up again, a new issue can be opened or this can be re-opened.
